### ISSUE TITLE
Max volume bar length

### ISSUE THREAD

**Issue by eduardohki** [johnhoran/Laine#21]
The width of the volume bar varies between applications with and without icons, it would be nice if they keep the same scale:

![laine_icons](https://cloud.githubusercontent.com/assets/7414593/7899281/887fd8ac-06f3-11e5-8904-58af2a1c5eab.png)

**Comment by johnhoran** [comment]
Yeah, I agree.  For whatever reason ALSA on my system has a generic icon, so I've never noticed this myself.  And as the icon is meant to double as a mute button also, there needs to be something there.  So rather than forcing the slider to be a certain size, it is probably better to force some generic icon to appear.

Thanks for the bug report.

**Comment by eduardohki** [comment]
Obs: I'm using Fedora 22.

**Comment by johnhoran** [comment]
Added a default icon in a0db067, which should be visible, and act as a mute button, if nothing else is available.
