### ISSUE TITLE
Doesn't integrate into aggregated menu in 3.20

### ISSUE THREAD

**Issue by eode** [johnhoran/Laine#34]
..title pretty much says it all.

**Comment by johnhoran** [comment]
It was something that was on my todo list after somebody requested it in #12 
I'm still planning on adding it and I'm most of the way there,  I just left the option in because some people were kind enough to help me with translations and I wanted to make sure that the translation was in place for when this was added.  And I have a little bit of free time at the moment so I should finish it up soon.  Anyway I'm going to close this in favour of the other issue.

Thanks for the report.

**Comment by eode** [comment]
Ah, I did check first, but missed that ticket.  ..thanks for the info, and for your work with Laine.
